# apiVersion: gitops.weave.works/v1alpha1
# kind: GitopsCluster
# metadata:
#   labels:
#     templates.weave.works/template-name: cluster-template-development-plus-kubelogin
#     templates.weave.works/template-namespace: default
#   name: botkube-demo
#   namespace: default
# spec:
#   capiClusterRef:
#     name: botkube-demo
# 
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  labels:
    templates.weave.works/template-name: cluster-template-development-plus-kubelogin
    templates.weave.works/template-namespace: default
  name: botkube-demo
  namespace: default
spec:
  controlPlaneRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: VCluster
    name: botkube-demo
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: VCluster
    name: botkube-demo

---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: VCluster
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: botkube-demo
    k3s_version: 1.28.5-k3s1
    minor_k8s_version: "1.28"
    templates.weave.works/template-name: cluster-template-development-plus-kubelogin
    templates.weave.works/template-namespace: default
  name: botkube-demo
  namespace: default
spec:
  controlPlaneEndpoint:
    host: botkube-demo.turkey.local
    port: 443
  helmRelease:
    values: |-
      vcluster:
        image: "rancher/k3s:v1.28.5-k3s1"
        extraArgs:
        - --kube-apiserver-arg=--oidc-issuer-url=https://dex.howard.moomboo.space
        - --kube-apiserver-arg=--oidc-client-id=wg-kubelogin
        - --kube-apiserver-arg=--oidc-groups-claim=groups
      syncer:
        extraArgs:
        - "--tls-san=botkube-demo.turkey.local"
      sync:
        nodes:
          enabled: true
        persistentvolumes:
          enabled: true
        # If you want to create custom storage classes
        # inside the vcluster.
        storageclasses:
          enabled: true
        ingresses:
          enabled: true
  kubernetesVersion: "1.28"
