apiVersion: gitops.weave.works/v1alpha1
kind: GitopsCluster
metadata:
  labels:
    templates.weave.works/template-name: cluster-template-development-plus-kubelogin
    templates.weave.works/template-namespace: ""
    weave.works/capi: bootstrap
  name: cluster-02
  namespace: default
spec:
  capiClusterRef:
    name: cluster-02

---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  labels:
    templates.weave.works/template-name: cluster-template-development-plus-kubelogin
    templates.weave.works/template-namespace: ""
  name: cluster-02
  namespace: default
spec:
  controlPlaneRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: VCluster
    name: cluster-02
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: VCluster
    name: cluster-02

---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: VCluster
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: cluster-02
    k3s_version: 1.26.1-k3s1
    minor_k8s_version: "1.26"
    templates.weave.works/template-name: cluster-template-development-plus-kubelogin
    templates.weave.works/template-namespace: ""
  name: cluster-02
  namespace: default
spec:
  controlPlaneEndpoint:
    host: cluster-02.turkey.local
    port: 443
  helmRelease:
    values: |-
      vcluster:
        image: "rancher/k3s:v1.26.1-k3s1"
        extraArgs:
        - --kube-apiserver-arg --oidc-issuer-url=https://dex.howard.moomboo.space
        - --kube-apiserver-arg --oidc-client-id=wg-kubelogin
        - --kube-apiserver-arg --oidc-groups-claim=groups
      syncer:
        extraArgs:
        - "--tls-san=cluster-02.turkey.local"
      sync:
        nodes:
          enabled: true
        persistentvolumes:
          enabled: true
        # If you want to create custom storage classes
        # inside the vcluster.
        storageclasses:
          enabled: true
        ingresses:
          enabled: true
  kubernetesVersion: "1.26"
