apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  labels:
    templates.weave.works/template-name: app-example
    templates.weave.works/template-namespace: default
  name: cluster-02
  namespace: default
  annotations:
    templates.weave.works/create-request: "{\"repository_url\":\"https://github.com/kingdon-ci/fleet-infra\",\"head_branch\":\"wge-create-branch-qpvvg\",\"title\":\"Create resource \",\"description\":\"This PR creates a app-example instance\",\"template_name\":\"app-example\",\"parameter_values\":{\"GIT_BRANCH\":\"master\",\"GIT_REPO_NAME\":\"podinfo\",\"NAMESPACE\":\"default\",\"PATH_TO_APPLY\":\"./kustomize/\",\"RESOURCE_NAME\":\"cluster-02\"},\"commit_message\":\"Create app-example instance\",\"credentials\":{},\"template_namespace\":\"vcluster\",\"template_kind\":\"GitOpsTemplate\"}"
spec:
  interval: 20s
  ref:
    branch: master
  url: https://github.com/<no value>/podinfo

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  labels:
    templates.weave.works/template-name: app-example
    templates.weave.works/template-namespace: default
  name: cluster-02
  namespace: default
spec:
  interval: 30s
  path: ./kustomize/
  prune: true
  sourceRef:
    kind: GitRepository
    name: podinfo
  targetNamespace: default
