apiVersion: gitops.weave.works/v1alpha1
kind: GitopsCluster
metadata:
  labels:
    templates.weave.works/template-name: cluster-template-k0s-plus-kubelogin
    templates.weave.works/template-namespace: default
    weave.works/capi: bootstrap
  name: cluster-03
  namespace: default
  annotations:
    templates.weave.works/create-request: "{\"repository_url\":\"https://github.com/kingdon-ci/fleet-infra\",\"head_branch\":\"wge-create-branch-wpihf\",\"base_branch\":\"main\",\"title\":\"Create resource cluster-03\",\"description\":\"This PR creates a cluster-template-k0s-plus-kubelogin instance\",\"template_name\":\"cluster-template-k0s-plus-kubelogin\",\"parameter_values\":{\"CLUSTER_NAME\":\"cluster-03\",\"K0S_VERSION\":\"v1.28.3-k0s.0\",\"NAMESPACE\":\"default\"},\"commit_message\":\"Create cluster-template-k0s-plus-kubelogin instance\",\"credentials\":{},\"template_namespace\":\"vcluster\",\"template_kind\":\"GitOpsTemplate\"}"
    templates.weave.works/created-files: "{\"files\":[\"clusters/howard-moomboo-space/clusters/default/cluster-03.yaml\"]}"
spec:
  capiClusterRef:
    name: cluster-03

---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  labels:
    templates.weave.works/template-name: cluster-template-k0s-plus-kubelogin
    templates.weave.works/template-namespace: default
  name: cluster-03
  namespace: default
spec:
  controlPlaneRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: VCluster
    name: cluster-03
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: VCluster
    name: cluster-03

---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: VCluster
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: cluster-03
    k0s_version: 1.28.3-k0s.0
    minor_k8s_version: "1.28"
    templates.weave.works/template-name: cluster-template-k0s-plus-kubelogin
    templates.weave.works/template-namespace: default
  name: cluster-03
  namespace: default
spec:
  controlPlaneEndpoint:
    host: cluster-03.turkey.local
    port: 443
  helmRelease:
    chart:
      name: vcluster-k0s
    values: |-
      vcluster:
        image: "k0sproject/k0s:v1.28.3-k0s.0"
        extraArgs:
        - --kubelet-extra-args --oidc-issuer-url=https://dex.howard.moomboo.space
        - --kubelet-extra-args --oidc-client-id=wg-kubelogin
        - --kubelet-extra-args --oidc-groups-claim=groups
      syncer:
        extraArgs:
        - "--tls-san=cluster-03.turkey.local"
      sync:
        nodes:
          enabled: true
        persistentvolumes:
          enabled: true
        # If you want to create custom storage classes
        # inside the vcluster.
        storageclasses:
          enabled: true
        ingresses:
          enabled: true
  kubernetesVersion: "1.28"
