apiVersion: gitops.weave.works/v1alpha1
kind: GitopsCluster
metadata:
  annotations:
    templates.weave.works/create-request: '{"repository_url":"https://github.com/kingdon-ci/fleet-infra","head_branch":"wge-create-branch-bvh9co","title":"Creates
      resource cluster-01","description":"This PR creates a cluster-template-development
      instance","template_name":"cluster-template-development","parameter_values":{"CLUSTER_NAME":"cluster-01","K3S_VERSION":"v1.25.6-k3s1","NAMESPACE":"default"},"commit_message":"Creates
      cluster-template-development instance","credentials":{},"values":[{"name":"external-secrets","version":"0.6.1","layer":"layer-0"},{"name":"flagger","version":"0.0.2","layer":"layer-2"},{"name":"kyverno","version":"0.0.5","layer":"layer-1"},{"name":"kyverno-policies","version":"0.0.5","layer":"layer-2"},{"name":"weave-policy-agent","version":"0.6.7","layer":"layer-1"}],"template_namespace":"vcluster","template_kind":"GitOpsTemplate"}'
  labels:
    templates.weave.works/template-name: cluster-template-development
    templates.weave.works/template-namespace: default
    weave.works/capi: bootstrap
  name: cluster-01
  namespace: default
spec:
  capiClusterRef:
    name: cluster-01

---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  labels:
    templates.weave.works/template-name: cluster-template-development
    templates.weave.works/template-namespace: default
  name: cluster-01
  namespace: default
spec:
  controlPlaneRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: VCluster
    name: cluster-01
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: VCluster
    name: cluster-01

---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: VCluster
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: cluster-01
    k3s_version: 1.25.6-k3s1
    minor_k8s_version: "1.25"
    templates.weave.works/template-name: cluster-template-development
    templates.weave.works/template-namespace: default
  name: cluster-01
  namespace: default
spec:
  controlPlaneEndpoint:
    host: cluster-01.turkey.local
    port: 443
  helmRelease:
    values: |-
      vcluster:
        image: "rancher/k3s:v1.25.6-k3s1"
      syncer:
        extraArgs:
        - "--tls-san=cluster-01.turkey.local"
      sync:
        nodes:
          enabled: true
        persistentvolumes:
          enabled: true
        # If you want to create custom storage classes
        # inside the vcluster.
        storageclasses:
          enabled: true
        ingresses:
          enabled: true
  kubernetesVersion: "1.25"
