apiVersion: gitops.weave.works/v1alpha1
kind: GitopsCluster
metadata:
  annotations:
    templates.weave.works/create-request: '{"repository_url":"https://github.com/kingdon-ci/fleet-infra","head_branch":"wge-create-branch-02cf79","title":"Creates
      resource somtochi","description":"This PR creates a cluster-template-development-plus-kubelogin
      instance","template_name":"cluster-template-development-plus-kubelogin","parameter_values":{"CLUSTER_NAME":"somtochi","K3S_VERSION":"v1.26.1-k3s1","KUBERNETES_VERSION":"1.26","NAMESPACE":"default"},"commit_message":"Creates
      cluster-template-development-plus-kubelogin instance","credentials":{},"template_namespace":"default","template_kind":"GitOpsTemplate"}'
  labels:
    templates.weave.works/template-name: cluster-template-development-plus-kubelogin
    templates.weave.works/template-namespace: default
    weave.works/capi: bootstrap
  name: somtochi
  namespace: default
spec:
  capiClusterRef:
    name: somtochi

---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  labels:
    templates.weave.works/template-name: cluster-template-development-plus-kubelogin
    templates.weave.works/template-namespace: default
  name: somtochi
  namespace: default
spec:
  controlPlaneRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: VCluster
    name: somtochi
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: VCluster
    name: somtochi

---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: VCluster
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: somtochi
    templates.weave.works/template-name: cluster-template-development-plus-kubelogin
    templates.weave.works/template-namespace: default
  name: somtochi
  namespace: default
spec:
  controlPlaneEndpoint:
    host: somtochi.turkey.local
    port: 443
  helmRelease:
    values: |-
      vcluster:
        image: "rancher/k3s:v1.26.1-k3s1"
        extraArgs:
        - --kube-apiserver-arg --oidc-issuer-url=https://dex.howard.moomboo.space
        - --kube-apiserver-arg --oidc-client-id=weave-gitops
        - --kube-apiserver-arg --oidc-groups-claim=groups
      syncer:
        extraArgs:
        - "--tls-san=somtochi.turkey.local"
      sync:
        nodes:
          enabled: true
        persistentvolumes:
          enabled: true
        # If you want to create custom storage classes
        # inside the vcluster.
        storageclasses:
          enabled: true
        ingresses:
          enabled: true
  kubernetesVersion: "1.26"
