apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: slack-bot
  namespace: cozy-fluxcd
spec:
  type: slack
  channel: gitops
  # address: https://slack.com/api/chat.postMessage
  secretRef:
    name: slack-bot-token
