apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: slack-bot
  namespace: cozy-fluxcd
spec:
  type: slack
  channel: general
  address: https://hooks.slack.com/services/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
  secretRef:
    name: slack-bot-token
