---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: my-secrets
  namespace: flux-system
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
  interval: 30s
  path: ./secrets/ossna23-demo
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
