apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: podinfo-canary
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  endpoints:
  - path: /metrics
    port: http
    interval: 5s
  namespaceSelector:
    matchNames:
    - test
  selector:
    matchLabels:
      app: podinfo-canary
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: podinfo-primary
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  endpoints:
    - path: /metrics
      port: http
      interval: 5s
  namespaceSelector:
    matchNames:
    - test
  selector:
    matchLabels:
      app: podinfo
