---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: water-monitor-dev
  namespace: default
spec:
  interval: 10m0s
  path: ./water-dev
  prune: true
  sourceRef:
    kind: GitRepository
    name: water-dev
