---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: water-dev
  namespace: cozy-fluxcd
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: water-monitor-ssh
  url: ssh://git@github.com/kingdonb/water-monitor.git
