apiVersion: helm.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: provider-helm-vcluster-moo
spec:
  credentials:
    secretRef:
      namespace: vcluster-moo-cluster
      name: moo-kubeconfig
      key: value
    source: Secret
