apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: public-ingress
  namespace: ingress-nginx
spec:
  interval: 30s
  timeout: 2m0s
  releaseName: ingress-public
  chart:
    spec:
      chart: ingress-nginx
      version: '4.x'
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: ingress-nginx
      interval: 15m
  values:
    controller:
      extraArgs:
        enable-ssl-passthrough: ""
        ingress-class: public
      electionID: public-ingress-leader
      ingressClassResource:
        name: public
        default: true
        controllerValue: "k8s.io/ingress-nginx-public"
      metrics:
        enabled: true
