apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: production-letsencrypt
spec:
  acme:
    email: kingdon@weave.works
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: production-letsencrypt-account-key
    solvers:
    - http01:
       ingress:
         class: public
