apiVersion: fluxcd.controlplane.io/v1
kind: FluxInstance
metadata:
  name: flux
  namespace: cozy-fluxcd
spec:
  distribution:
    version: "2.2.x"
    registry: "ghcr.io/fluxcd"
  cluster:
    type: kubernetes
  sync:
    kind: GitRepository
    url: "https://github.com/kingdon-ci/fleet-infra.git"
    ref: "refs/heads/main"
    path: "clusters/harvey-moomboo-space"
    pullSecret: "flux-system"
