apiVersion: fluxcd.controlplane.io/v1
kind: FluxInstance
metadata:
  name: flux
  namespace: cozy-fluxcd
spec:
  distribution:
    version: "2.4.x"
    registry: "ghcr.io/fluxcd"
  cluster:
    type: kubernetes
  sync:
    kind: GitRepository
    url: "https://github.com/kingdon-ci/fleet-infra.git"
    ref: "refs/heads/main"
    path: "clusters/harvey-moomboo-space"
    pullSecret: "flux-system"
  kustomize:
    patches:
      - patch: |
          apiVersion: networking.k8s.io/v1
          kind: NetworkPolicy
          spec:
            ingress:
              - from:
                - ipBlock:
                    cidr: 10.244.0.0/16
            podSelector:
              matchLabels:
                app: notification-controller
            policyTypes:
            - Ingress
        target:
          kind: NetworkPolicy
          name: allow-webhooks
      # - patch: |
      #     - op: add
      #       path: /spec/template/spec/containers/0/args/-
      #       value: --concurrent=20
      #     - op: add
      #       path: /spec/template/spec/containers/0/args/-
      #       value: --requeue-dependency=5s
      #     - op: replace
      #       path: /spec/template/spec/containers/0/resources/limits
      #       value:
      #         cpu: 2000m
      #         memory: 2048Mi
      #   target:
      #     kind: Deployment
      #     name: (kustomize-controller|helm-controller|source-controller)
      - patch: |
          - op: add
            path: /spec/template/spec/containers/0/args/-
            value: --storage-adv-addr=source-controller.cozy-fluxcd.svc
          - op: add
            path: /spec/template/spec/containers/0/args/-
            value: --events-addr=http://notification-controller.cozy-fluxcd.svc/
        target:
          kind: Deployment
          name: source-controller
      - patch: |
          - op: add
            path: /spec/template/spec/containers/0/args/-
            value: --events-addr=http://notification-controller.cozy-fluxcd.svc/
        target:
          kind: Deployment
          name: (kustomize-controller|helm-controller|image-reflector-controller|image-automation-controller)
