apiVersion: fluxcd.controlplane.io/v1
kind: FluxInstance
metadata:
  name: flux
  namespace: cozy-fluxcd
spec:
  distribution:
    version: "2.4.x"
    registry: "ghcr.io/fluxcd"
  cluster:
    type: kubernetes
  sync:
    kind: GitRepository
    url: "https://github.com/kingdon-ci/fleet-infra.git"
    ref: "refs/heads/main"
    path: "clusters/harvey-moomboo-space"
    pullSecret: "flux-system"
  kustomize:
    patches:
      - patch: |
          apiVersion: networking.k8s.io/v1
          kind: NetworkPolicy
          metadata:
            name: all
          spec:
            ingress:
              - from:
                - ipBlock:
                    cidr: 10.244.0.0/16
            podSelector:
              matchLabels:
                app: notification-controller
            policyTypes:
            - Ingress
        target:
          kind: NetworkPolicy
          name: allow-webhooks
          namespace: cozy-fluxcd
