---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: podinfo
  namespace: flux-system
spec:
  interval: 10m0s
  timeout: 1m0s
  suspend: false
  retryInterval: 1m30s
  targetNamespace: default
  path: ./examples/podinfo-simple
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
