---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: podinfo
  namespace: flux-system
spec:
  interval: 30s
  timeout: 1m0s
  suspend: false
  retryInterval: 1m30s
  path: ./examples/podinfo-canary
  prune: true
  dependsOn:
    - name: prometheus-kube
    - name: flagger
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
