apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
  name: webhook-receiver
  namespace: cozy-fluxcd
spec:
  ingressClassName: nginx
  rules:
  - host: webhook.harvey.moomboo.space
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: webhook-receiver
            port:
              number: 80
  tls:
    - hosts:
        - webhook.harvey.moomboo.space
      secretName: webhook-receiver-https
