---
apiVersion: notification.toolkit.fluxcd.io/v1
kind: Receiver
metadata:
  name: harvey-fleet-infra
  namespace: cozy-fluxcd
spec:
  resources:
  - apiVersion: source.toolkit.fluxcd.io/v1
    kind: GitRepository
    name: cozy-fluxcd
  secretRef:
    name: fleet-infra-webhook
  type: github
  events:
    - "ping"
    - "push"
