---
apiVersion: notification.toolkit.fluxcd.io/v1
kind: Receiver
metadata:
  name: harvey-water-myapp-img
  namespace: cozy-fluxcd
spec:
  resources:
  - kind: ImageRepository
    name: myapp
  secretRef:
    name: water-monitor-img-webhook
  type: github
  events:
    - "package"
