apiVersion: v1
kind: Secret
metadata:
    name: metrics-secret
    namespace: grafana
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:nuSAys18HxCuWVI1IB3/EshlBWgrXu0uUHNx9oaWaWs4rAvVDT7TQpdJ/6ktRcAwKS4LKVDCfFUrqu/4Ix7fgJ5xxoKyv5VSLCLnxVH6rVZhJdiIIztulicOZhfzqkx8O83rd5QI7A3DdUNYP+pbOwFXO+LuEudidHa4qCnkWds=,iv:jF2pXnU9pZQ4U+8zH+BJMYHewBQObUMN7zJhcTUEx40=,tag:HMoA4lx2eWHszEbWlKPw9w==,type:str]
    username: ENC[AES256_GCM,data:mGrKPIYRZA==,iv:+8IHfNjkTWFwPPXMMqqhSBjh3Vp5S6APC+TcQgouSx8=,tag:qbjClhqkWeLV9ZifyP/JtA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-06-12T18:12:59Z"
    mac: ENC[AES256_GCM,data:CEn2kL+dWc//MEZV2+1Gpv5OAeWFIYyl785xQRxFwc41sEdt95KEEMEeOXHl/hCxw0CWOPR/2+5M3VUjn7J2MWT+9fMt8A/lSwl3jwneDePfbPWVTUDIIkj23+fJjgYAuTBtVXnBId9oYFDL44JbDtenO/aQ53NzIwvrd7W0Rso=,iv:pMkWLPyJ4CkZR58bx9tOt7d0BlUOJGiYaNZ8p2poo3I=,tag:8cpUYsTzMMKv3DS9t90hlA==,type:str]
    pgp:
        - created_at: "2023-06-12T18:12:58Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0rIHLPhXX+sAQ//c529WrT8E1YhjjlnDaYrTUYtaT18U1TCLn9jT3ceXylY
            tknU2jX3mFMnxvavAWoxojGQXO1vgMrsHce4Z3H2gTypplisQ3toTI99ndJ7uWPd
            O3U1F6iqMO9+Gp+ayLtBDmD5r4RvQGORPuAR2+8/f2zJNZIFfQL1qV7tVvSqjlbF
            HxuYLqTMaQv8gxxPTk30PFay8yYDuFc7VHtL2h4/AFhgrG6jykkKVivGKGatAq4J
            cXOWQqn4ifG9EzVZjeRRf5na4S7hGo7Cz47nFxZIPDXkHQX8GSSD2KTEMNsyv6lQ
            kOOpZJqQVuY1kKB7+iGChuR4ubrefhNNKHyDhNfLKNdh550hIxoqGvaQoIUcHXWt
            LrnLZp5FVdyirl5RFtQUe2lKhMy1/Uy1ngjStPgI8bUenZT5n1CVUBOhYBChGRtM
            qlM565V9mXs8dwZjDTk5zfTduWla5po75XXCfgLfQt7Yf+xYD6RPV3z7KX6pHlGn
            SqdOsn1bG+h9mUHHp5b5rANnOw1gUe+5dpiO0xqbrJyNHgDboejYYC/A2zAcLIUx
            k1TCCGh12Sgv2oqgXVMmDltfWX1PMEB+GhTfGt6YAuFGcqG5ulYac9wieSQ6QOEn
            wrvQ0YdhC7IVFzgQHbE0f1SprXPN55uEtQD/AtuWGMtHw3HpGPdWojXN0YcWASzU
            ZgEJAhDUp7fUik3+Wpvx/CjItCB/ZPoRDPO2Nn1h4uXTqUg3qQw1sK6IYnHtQ7C9
            bYNAntPraYxUz5bO7E2KrxhRU2DsppaB5rPs3Jge6gI6NC3RVJOAt6kvVEpR228I
            OKkxHEZZrg==
            =4GFE
            -----END PGP MESSAGE-----
          fp: BF333F5B18A7B7E64ABF8ECD3DA73AD3A17399DC
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
apiVersion: v1
kind: Secret
metadata:
    name: logs-secret
    namespace: grafana
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:viOzSFC8/wrIEge3wBF6nj3LQJnV0gtwvnl0VmPD3p94Mea0aktNSrItBbOHz9utyrqyu2cX3IXVzF/BEUumYaQLupq2K9Gpq5MDB2CS32lhrB7sc+osZ/AEeMfIMikD4fSphw8HUJc2LKXSQ4+m8Tu54Q2Vp6E3+ttmJy7LueI=,iv:QxaMsIwrbGCdEaqD7/cr7Wo8vt0o6JKUBUNX6ngT+TY=,tag:dLBEBjMtqdJYUaNbHcQ4cA==,type:str]
    username: ENC[AES256_GCM,data:y3k09IOk,iv:CLo5j64W112+RJJ4G9BIjiBN46slzjuLInLM1RIMvyk=,tag:gT6XqEnle6IHsfNCjLug2w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-06-12T18:12:59Z"
    mac: ENC[AES256_GCM,data:CEn2kL+dWc//MEZV2+1Gpv5OAeWFIYyl785xQRxFwc41sEdt95KEEMEeOXHl/hCxw0CWOPR/2+5M3VUjn7J2MWT+9fMt8A/lSwl3jwneDePfbPWVTUDIIkj23+fJjgYAuTBtVXnBId9oYFDL44JbDtenO/aQ53NzIwvrd7W0Rso=,iv:pMkWLPyJ4CkZR58bx9tOt7d0BlUOJGiYaNZ8p2poo3I=,tag:8cpUYsTzMMKv3DS9t90hlA==,type:str]
    pgp:
        - created_at: "2023-06-12T18:12:58Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0rIHLPhXX+sAQ//c529WrT8E1YhjjlnDaYrTUYtaT18U1TCLn9jT3ceXylY
            tknU2jX3mFMnxvavAWoxojGQXO1vgMrsHce4Z3H2gTypplisQ3toTI99ndJ7uWPd
            O3U1F6iqMO9+Gp+ayLtBDmD5r4RvQGORPuAR2+8/f2zJNZIFfQL1qV7tVvSqjlbF
            HxuYLqTMaQv8gxxPTk30PFay8yYDuFc7VHtL2h4/AFhgrG6jykkKVivGKGatAq4J
            cXOWQqn4ifG9EzVZjeRRf5na4S7hGo7Cz47nFxZIPDXkHQX8GSSD2KTEMNsyv6lQ
            kOOpZJqQVuY1kKB7+iGChuR4ubrefhNNKHyDhNfLKNdh550hIxoqGvaQoIUcHXWt
            LrnLZp5FVdyirl5RFtQUe2lKhMy1/Uy1ngjStPgI8bUenZT5n1CVUBOhYBChGRtM
            qlM565V9mXs8dwZjDTk5zfTduWla5po75XXCfgLfQt7Yf+xYD6RPV3z7KX6pHlGn
            SqdOsn1bG+h9mUHHp5b5rANnOw1gUe+5dpiO0xqbrJyNHgDboejYYC/A2zAcLIUx
            k1TCCGh12Sgv2oqgXVMmDltfWX1PMEB+GhTfGt6YAuFGcqG5ulYac9wieSQ6QOEn
            wrvQ0YdhC7IVFzgQHbE0f1SprXPN55uEtQD/AtuWGMtHw3HpGPdWojXN0YcWASzU
            ZgEJAhDUp7fUik3+Wpvx/CjItCB/ZPoRDPO2Nn1h4uXTqUg3qQw1sK6IYnHtQ7C9
            bYNAntPraYxUz5bO7E2KrxhRU2DsppaB5rPs3Jge6gI6NC3RVJOAt6kvVEpR228I
            OKkxHEZZrg==
            =4GFE
            -----END PGP MESSAGE-----
          fp: BF333F5B18A7B7E64ABF8ECD3DA73AD3A17399DC
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
