apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
patches:
- target:
    kind: Deployment
    name: kustomize-controller
  patch: |-
  - op: add
    path: /spec/template/spec/containers/0/args/-
    value: --requeue-dependency=3s
  - op: add
    path: /spec/template/spec/containers/0/args/0
    value: --concurrent=6
