apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- helm.toolkit.fluxcd.io_helmreleases.yaml
- gotk-components.yaml
- gotk-sync.yaml
patches:
- target:
    kind: Deployment
    name: kustomize-controller
  patch: |-
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: --requeue-dependency=3s
    - op: add
      path: /spec/template/spec/containers/0/args/0
      value: --concurrent=6
- patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: helm-controller
        namespace: flux-system
      spec:
        template:
          spec:
            containers:
            - name: manager
              image: kingdonb/helm-controller:113bf54
              args:
                - --events-addr=http://notification-controller.flux-system.svc.cluster.local./
                - --watch-all-namespaces=true
                - --log-level=debug
                - --log-encoding=json
                - --enable-leader-election
                - --feature-gates=DetectDrift=True
  target:
    kind: Deployment
    name: "helm-controller"
