apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: crossplane-contrib-provider-helm
spec:
  package: xpkg.upbound.io/crossplane-contrib/provider-helm:v0.17.0
  runtimeConfigRef:
    apiVersion: pkg.crossplane.io/v1beta1
    kind: ProviderConfig
    name: provider-helm-vcluster-moo
---
apiVersion: helm.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: provider-helm-vcluster-moo
spec:
  credentials:
    secretRef:
      namespace: vcluster-moo-cluster
      name: moo-kubeconfig
      key: value
    source: Secret
