apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  labels:
    templates.weave.works/template-name: app-example
    templates.weave.works/template-namespace: ""
  name: example-01
  namespace: default
spec:
  interval: 20s
  ref:
    branch: master
  url: https://github.com/stefanprodan/podinfo

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  labels:
    templates.weave.works/template-name: app-example
    templates.weave.works/template-namespace: ""
  name: example-01
  namespace: default
spec:
  interval: 30s
  path: ./kustomize/
  prune: true
  sourceRef:
    kind: GitRepository
    name: example-01
  targetNamespace: default
