apiVersion: v1
kind: Namespace
metadata:
  labels:
    templates.weave.works/template-name: big-example
    templates.weave.works/template-namespace: ""
  name: podinfo
  namespace: default

---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  labels:
    templates.weave.works/template-name: big-example
    templates.weave.works/template-namespace: ""
  name: example-02
  namespace: default
spec:
  interval: 20s
  ref:
    branch: master
  url: https://github.com/kingdonb/podinfo

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  labels:
    templates.weave.works/template-name: big-example
    templates.weave.works/template-namespace: ""
  name: example-02
  namespace: default
spec:
  interval: 30s
  path: ./deploy/overlays/flux-oci
  prune: true
  sourceRef:
    kind: GitRepository
    name: example-02
