apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
# - helm.toolkit.fluxcd.io_helmreleases.yaml
- gotk-components.yaml
- gotk-sync.yaml
patches: []
  # - patch: |
  #       apiVersion: apps/v1
  #       kind: Deployment
  #       metadata:
  #         name: helm-controller
  #         namespace: flux-system
  #       spec:
  #         template:
  #           spec:
  #             containers:
  #             - name: manager
  #               image: kingdonb/helm-controller:842a942
