---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana-agent-operator
  namespace: flux-system
spec:
  chart:
    spec:
      chart: grafana-agent-operator
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: grafana
  # install:
  #   createNamespace: true
  interval: 1m0s
    # HelmRelease is suspended to get metrics use under control
  suspend: true
  releaseName: grafana-agent-operator
  targetNamespace: grafana
  storageNamespace: grafana
