apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  example.server: |
    howard.moomboo.stage {
      hosts {
          98.227.195.144 howard.moomboo.stage
          fallthrough
      }
      whoami
    }
