apiVersion: templates.weave.works/v1alpha2
kind: GitOpsTemplate
metadata:
  name: app-example
  namespace: vcluster
  annotations:
    # templates.weave.works/kustomizations-enabled: "true"
  labels:
    weave.works/template-type: application
spec:
  description: Simple example app
  renderType: templating
  params:
    - name: RESOURCE_NAME
      description: Unique name for the created resources
      options: [example-01,example-02]
      default: example-02
      required: true
    - name: USER
      description: Git owner containing the repository
      options: [kingdonb,stefanprodan,"kingdon-ci",juozasg]
      default: "stefanprodan"
      required: true
    - name: REPO
      required: true
      description: Git repository containing the application
      default: "podinfo"
    - name: GIT_BRANCH
      required: true
      description: Git branch to deploy from
      default: "master"
    - name: NAMESPACE
      required: true
      description: Deploy to namespace
      default: "default"
    - name: PATH_TO_APPLY
      required: true
      description: Path in the Git repository
      default: "./kustomize/"
  resourcetemplates:
    - content:
        - apiVersion: source.toolkit.fluxcd.io/v1beta2
          kind: GitRepository
          metadata:
            name: "{{ .params.RESOURCE_NAME }}"
            namespace: "{{ .params.NAMESPACE }}"
          spec:
            interval: 20s
            url: 'https://github.com/{{ .params.USER }}/{{ .params.REPO }}'
            ref:
              branch: "{{ .params.GIT_BRANCH }}"
        - apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
          kind: Kustomization
          metadata:
            name: "{{ .params.RESOURCE_NAME }}"
            namespace: "{{ .params.NAMESPACE }}"
          spec:
            interval: 30s
            targetNamespace: "{{ .params.NAMESPACE }}"
            path: "{{ .params.PATH_TO_APPLY }}"
            prune: true
            sourceRef:
                kind: GitRepository
                name: "{{ .params.GIT_REPO_NAME }}"
