---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: weave-gitops-quickstart
  namespace: flux-system
spec:
  interval: 10m0s
  ref:
    branch: main
  url: https://github.com/weaveworks/weave-gitops-quickstart
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: quickstart-templates
  namespace: flux-system
spec:
  chart:
    spec:
      chart: "quickstart-templates"
      version: ">=0.1.0"
      sourceRef:
        kind: GitRepository
        name: weave-gitops-quickstart
        namespace: flux-system
  interval: 10m0s
