---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 10m0s
  timeout: 1m0s
  # suspend: true
  retryInterval: 1m30s
  # targetNamespace: cert-manager
  path: ./examples/cert-manager/staging
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
