---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cert-issuers
  namespace: flux-system
spec:
  dependsOn:
    - name: cert-manager
  interval: 10m0s
  timeout: 1m0s
  retryInterval: 1m30s
  path: ./examples/cert-manager/staging
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
