---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 30s
  timeout: 1m0s
  retryInterval: 1m30s
  path: ./examples/cert-manager/1.11.0
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
