---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kwasm-operator
  namespace: wasm-test
spec:
  chart:
    spec:
      chart: kwasm-operator
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: kwasm-operator
        namespace: wasm-test
  install:
    createNamespace: true
  interval: 1m0s
  releaseName: kwasm
  targetNamespace: kwasm
