apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-webhooks
  namespace: "cozy-fluxcd"
spec:
  policyTypes:
    - Ingress
  ingress:
    - from:
        - ipBlock:
            cidr: 10.243.0.0/16
        - ipBlock:
            cidr: 10.244.0.0/16
        - namespaceSelector: {}
  podSelector:
    matchLabels:
      app: notification-controller
