---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flagger
  namespace: flux-system
spec:
  interval: 30s
  timeout: 1m0s
  suspend: false
  retryInterval: 1m30s
  targetNamespace: monitoring
  path: ./examples/flagger
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
