apiVersion: gitops.weave.works/v1alpha1
kind: GitopsCluster
metadata:
  name: limnocentral
  namespace: ext
  # Signals that this cluster should be bootstrapped.
  # labels:
  #   weave.works/capi: bootstrap
spec:
  secretRef:
    name: limnocentral-kubeconfig
