---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: home-guests-cluster-role-binding
subjects:
  - kind: Group
    name: kingdon-ci:home-guests
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: home-guests-cluster-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: home-guests-cluster-role
rules:
  - apiGroups: ["gitops.weave.works"]
    resources: ["gitopsclusters"]
    verbs: ["get", "list", "watch"]
