---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: crossplane-vcluster
  namespace: cozy-fluxcd
spec:
  interval: 2m30s
  timeout: 1m0s
  suspend: false
  retryInterval: 1m30s
  path: ./examples/crossplane-vcluster
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: cozy-fluxcd
    namespace: cozy-fluxcd
