---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kargo
  namespace: kargo
spec:
  chartRef:
    kind: OCIRepository
    name: kargo-chart
  interval: 10m0s
  driftDetection:
    mode: enabled
  values:
    api:
      adminAccount:
        passwordHash: '$2a$10$Zrhhie4vLz5ygtVSaif6o.qN36jgs6vjtMBdM6yrU1FOeiAAMMxOm'
        tokenSigningKey: iwishtowashmyirishwristwatch
