---
apiVersion: notification.toolkit.fluxcd.io/v1
kind: Receiver
metadata:
  name: fleet-infra
  namespace: flux-system
spec:
  resources:
  - apiVersion: source.toolkit.fluxcd.io/v1beta2
    kind: GitRepository
    name: fleet-infra
  secretRef:
    name: fleet-infra-webhook
  type: github
  events:
    - "ping"
    - "push"
