apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-webhooks-from-outside
  namespace: flux-system
spec:
  ingress: {}
  podSelector:
    matchLabels:
      app: notification-controller
  policyTypes:
  - Ingress
