---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: monitoring
  namespace: monitoring
spec:
  interval: 30m0s
  ref:
    branch: ossna23
  url: https://github.com/kingdonb/flux2
