---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: spin-operator
spec:
  chart:
    spec:
      chart: spin-operator
      version: 0.1.0
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: spinkube
  interval: 10m0s
