---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: weave-gitops
  namespace: flux-system
spec:
  dependsOn:
    - name: cert-manager
  interval: 10m0s
  timeout: 1m0s
  # suspend: true
  retryInterval: 1m30s
  targetNamespace: flux-system
  path: ./examples/weave-gitops
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  patches:
    - patch: |-
        apiVersion: helm.toolkit.fluxcd.io/v1beta2
        kind: HelmRelease
        metadata:
          name: not-used
        spec:
          suspend: true
      target:
        kind: HelmRelease
        name: weave-gitops-enterprise
        namespace: flux-system
