---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nginx
  namespace: flux-system
spec:
  interval: 10m0s
  timeout: 1m0s
  suspend: true
  retryInterval: 1m30s
  targetNamespace: ingress-nginx
  path: ./examples/nginx-ingress
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
