---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: flux-2-1
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: flux-cli
  #filterTags:
  #  pattern: '^v2\.1\.[0-9]+$'
  policy:
    semver:
      range: 2.1.x
