# Not released yet - k3s 1.28.x
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: k3s-1-28
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: k3s
  filterTags:
    pattern: '^v1\.28\.[0-9]+-k3s[0-9]+$'
  policy:
    semver:
      range: 1.28.x-0
